import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Image from "next/image";
import Card from "../components/Card";

const cardProps = {
  title: "Meo Anh Quoc",
  link: "/abc/cd",
  linkImage: "/static/cat.png",
};

export default function Home() {
  const handleOnClickBtn = () => {
    console.log("Click");
  };

  const bannerProps = {
    title1: "SPAM",
    title2: "My App",
    subtitle: "Discover For My App",
    buttonText: "Get App",
    actionClick: handleOnClickBtn,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner {...bannerProps} />
        <Image
          className={styles.pictureMain}
          src="/static/cat.png"
          alt="picture"
          width={300}
          height={300}
        />
        <Card {...cardProps} />
      </main>
    </div>
  );
}
