import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Image from "next/image";
import Card from "../components/Card";
import { fetchCatsCollection } from "../libs/cats-collection";
import { DEFAULT_IMAGE } from "../constants";
import useTrackLocation from "./../hooks/useTrackLocation";

export default function Home(props) {
  const { trackYouLocation } = useTrackLocation();
  const handleOnClickBtn = () => {
    trackYouLocation();
  };

  const bannerProps = {
    title1: "CATs",
    title2: "Collection",
    subtitle: "Discover For My App",
    buttonText: "Get App",
    actionClick: handleOnClickBtn,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner {...bannerProps} />
        <Image
          className={styles.pictureMain}
          src="/static/cat.png"
          alt="picture"
          width={200}
          height={200}
        />
        {props.data.length > 0 && (
          <>
            <h2 className={styles.cardHeader}>Coffee Ahaha</h2>
            <div className={styles.card_container}>
              {props.data.map((card) => (
                <Card
                  key={card.id}
                  title={card.name}
                  link={`/cat-collections/${card.id}`}
                  linkImage={card.imgUrl || DEFAULT_IMAGE}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetchCatsCollection();

  if (!data.length) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data,
    },
  };
}
